<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Copyright>Copyright 2014-Present Facebook, Inc</Copyright>
    <AssemblyTitle>ReactJS.NET Unit Tests</AssemblyTitle>
    <Authors>Daniel Lo Nigro</Authors>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>React.Tests</AssemblyName>
    <AssemblyOriginatorKeyFile>../../src/key.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
    <PackageId>React.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\React.Core\React.Core.csproj" />
  </ItemGroup>



  <ItemGroup>
    <ProjectReference Include="..\..\src\React.Router\React.Router.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="Moq" Version="4.8.3" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
  </ItemGroup>



  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

</Project>
